# Generated by Django 5.2.8 on 2025-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='score',
            name='title',
        ),
        migrations.AlterField(
            model_name='score',
            name='body',
            field=models.FloatField(default=0.0),
        ),
    ]
