# Generated by Django 5.2.8 on 2025-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_remove_score_slug_remove_score_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='title',
            field=models.CharField(default='no title', max_length=75),
        ),
    ]
