# Generated by Django 5.2.8 on 2025-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_score_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hra',
            field=models.CharField(default='nazev hry', max_length=75),
        ),
    ]
