# Generated by Django 5.2.8 on 2025-11-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Score',
        ),
    ]
