# Generated by Django 5.2.8 on 2025-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_score_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.CharField(default='scored points', max_length=75),
        ),
    ]
